### ISSUE TITLE
missing tosca type for torpedo (eg: ubuntu is missing)

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#484]
### Torpedo

``` yaml
!ruby/object:Megam::Assembly
      id: ASM1258771041770143744
      name: antirrhinums
      tosca_type: tosca.torpedo.
      components: []
      requirements: []
      policies: []
      inputs:
      - key: domain
        value: megambox.com
      - key: sshkey
        value: kish
      - key: provider
        value: one
      - key: cpu
        value: '0.5'
      - key: ram
        value: '896'
      - key: version
        value: '7.0'

```

We need the following
- tosca.torpedo.ubuntu
- tosca.torpedo.debian
- tosca.torpedo.coreos
- tosca.torpdedo.centos
### Service

``` yaml
!ruby/object:Megam::Assembly
      id: ASM1258772197330255872
      name: groundhogs
      tosca_type: tosca.service.ubuntu
      components:
      - !ruby/object:Megam::ComponentsCollection
        components:
        - !ruby/object:Megam::Components
          id: COM1258772197338644480
          name: aflame
          tosca_type: tosca.service.
          inputs:
          - key: domain
            value: megambox.com
          - key: version
            value: '9.3'
          - key: source
            value: ''
          - key: lastsuccessstatusupdate
            value: 2015-09-24 10:01:32.787320735 +0000 UTC

```

@rajthilakmca  fyi.
